name: zzc 部署到 GitHub Pages

on:
  push:
    branches: [ main ]  # 你代码的主分支，可改成 master
  workflow_dispatch:     # 允许手动触发部署

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 构建项目
        run: npm run build

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
